"use client";

import Link from "next/link";
import { Mail, ShieldCheck, UserPlus, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { Button, PageHeader, SectionTitle, TextInput } from "@/components/ui";

type Staff = { id: string; email: string; name: string; role: string; joined_at?: string; last_login_at?: string; suspended: boolean; status: string };
type Invite = { id: string; email: string; name: string; role: string; invited_at: string; expires_at: string; accepted_at?: string | null; revoked_at?: string | null };

async function staffApi(path: string, init?: RequestInit) {
  const response = await fetch(`/api/v1/admin-auth${path}`, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Staff request failed."); return body;
}

export default function StaffPage() {
  const [admin, setAdmin] = useState<{ role?: string } | null>(null); const [staff, setStaff] = useState<Staff[]>([]); const [invites, setInvites] = useState<Invite[]>([]); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = () => void Promise.all([staffApi("/session"), staffApi("/staff"), staffApi("/staff/invites")]).then(([session, staffResult, inviteResult]) => { setAdmin(session.admin); setStaff(staffResult.staff || []); setInvites(inviteResult.invites || []); }).catch((e) => setError(e instanceof Error ? e.message : "Admin authentication required."));
  useEffect(load, []);
  const invite = async () => { setError(""); setMessage(""); try { await staffApi("/staff/invites", { method: "POST", body: JSON.stringify({ email, name, role: "admin", permissions: { admin: true, users: true, badges: true, reports: true, staff: false } }) }); setEmail(""); setName(""); setMessage("Invitation sent."); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not send invitation."); } };
  if (error && !admin) return <main className="grid min-h-[100svh] place-items-center bg-[#07070a] px-5 text-white"><div className="surface rounded-2xl p-8 text-center"><ShieldCheck className="mx-auto mb-4 text-red-300" /><p className="text-sm text-zinc-400">{error}</p><Link href="/admin/login" className="mt-5 inline-flex rounded-xl bg-[#9b87f5] px-4 py-2.5 text-sm">Admin login</Link></div></main>;
  return <main className="mx-auto min-h-screen max-w-[1200px] px-5 py-8 text-white sm:px-8 sm:py-11"><PageHeader eyebrow="Administration" title="Staff" description="Manage invited administrators and their access." action={<span className="flex gap-3"><Link href="/admin/sessions" className="text-sm text-[#b1a5ff] hover:text-white">Sessions</Link><Link href="/admin" className="text-sm text-[#b1a5ff] hover:text-white">Back to admin</Link></span>} />{error && <p className="mb-4 text-xs text-red-300">{error}</p>}{message && <p className="mb-4 text-xs text-emerald-400">{message}</p>}<div className="grid gap-6 lg:grid-cols-2"><section className="surface rounded-2xl p-5 sm:p-6"><SectionTitle icon={Users} title="Active staff" description="Root access is protected and cannot be removed here." /><div className="space-y-2">{staff.map((item) => <div key={item.id} className="rounded-xl border border-white/[.06] p-3 text-xs"><div className="flex items-center gap-2"><span className="text-zinc-200">{item.name || "Unnamed administrator"}</span><span className="rounded-full bg-[#9b87f5]/10 px-2 py-1 text-[10px] uppercase text-[#b8acff]">{item.role}</span></div><p className="mt-1 text-zinc-500">{item.email}</p><p className="mt-1 text-zinc-600">Joined {new Date(item.joined_at || "").toLocaleDateString()} · Last login {item.last_login_at ? new Date(item.last_login_at).toLocaleString() : "Never"}</p></div>)}{!staff.length && <p className="text-xs text-zinc-600">No staff accounts.</p>}</div></section><section className="surface rounded-2xl p-5 sm:p-6"><SectionTitle icon={UserPlus} title="Invite administrator" description={admin?.role === "super_admin" ? "Only the root administrator can send invites." : "Super Administrator access is required."} />{admin?.role === "super_admin" && <div className="space-y-3"><TextInput value={name} onChange={setName} placeholder="Full name" /><div className="relative"><Mail size={15} className="absolute left-3 top-3.5 text-zinc-600" /><TextInput value={email} onChange={setEmail} type="email" placeholder="admin@example.com" className="pl-9" /></div><Button variant="accent" disabled={!name.trim() || !email.trim()} onClick={() => void invite()}>Send invite</Button></div>}</section><section className="surface rounded-2xl p-5 sm:p-6 lg:col-span-2"><SectionTitle icon={Mail} title="Pending invites" description="Invitations expire after 24 hours and are single-use." /><div className="space-y-2">{invites.filter((item) => !item.accepted_at && !item.revoked_at).map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-white/[.06] p-3 text-xs"><span className="text-zinc-200">{item.name}</span><span className="text-zinc-500">{item.email}</span><span className="text-zinc-600">Expires {new Date(item.expires_at).toLocaleString()}</span></div>)}{!invites.filter((item) => !item.accepted_at && !item.revoked_at).length && <p className="text-xs text-zinc-600">No pending invites.</p>}</div></section></div></main>;
}
