import "server-only";
import type { PoolClient } from "pg";
import type { NextRequest } from "next/server";
import { AdminError,requireAdminSession } from "./admin-auth";
import { database,one } from "./postgres";
export const STAFF_SECTIONS=["users","constellations","bans","reserved","banned","badges","premium","reports","flags","bakaboost","themes","templates","fonts","audit"];
export function adminSection(path:string[]){const tail='/'+path.join('/');if(tail.startsWith('/access')||tail.startsWith('/staff'))return null;if(tail.includes('/badges')||tail.startsWith('/verification')||tail.startsWith('/badge-platform'))return 'badges';return ({users:'users',constellations:'constellations',bans:'bans','reserved-usernames':'reserved','banned-words':'banned',entitlements:'premium',reports:'reports','feature-flags':'flags',bakaboost:'bakaboost',themes:'themes',templates:'templates',fonts:'fonts','audit-logs':'audit'} as Record<string,string>)[path[0]]||null;}
export async function authorizeAdmin(request:NextRequest,path:string[]){const account=await requireAdminSession(request),role=account.role==='super_admin'?'owner':account.role;if(!['owner','admin','moderator'].includes(role))throw new AdminError('Administrator access is required.',403);if(path[0]==='access'&&!['GET','HEAD'].includes(request.method)&&role!=='owner')throw new AdminError('Only owners can change role access.',403);if(path[0]==='staff'&&!['owner','admin'].includes(role))throw new AdminError('You cannot assign staff roles.',403);const section=adminSection(path);if(section&&role!=='owner'){const row=await one<{enabled:boolean}>("SELECT enabled FROM staff_section_access WHERE role=$1 AND section=$2",[role,section]);if(row?.enabled===false)throw new AdminError('You do not have access to this section.',403);}return {...account,staffRole:role};}
export async function sectionAccess(){const result:Record<string,Record<string,boolean>>={admin:Object.fromEntries(STAFF_SECTIONS.map(key=>[key,true])),moderator:Object.fromEntries(STAFF_SECTIONS.map(key=>[key,true]))};const rows=await database().query<{role:string;section:string;enabled:boolean}>("SELECT role,section,enabled FROM staff_section_access");for(const row of rows.rows)if(result[row.role]&&STAFF_SECTIONS.includes(row.section))result[row.role][row.section]=row.enabled;return result;}
export async function adminTransaction<T>(work:(db:PoolClient)=>Promise<T>){const db=await database().connect();try{await db.query('BEGIN');const result=await work(db);await db.query('COMMIT');return result;}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
export async function audit(db:PoolClient,actor:string,action:string,type:string,target:string,metadata:unknown={}){await db.query("INSERT INTO audit_logs (actor_user_id,action,target_type,target_id,metadata) VALUES ($1,$2,$3,$4,$5::jsonb)",[actor,action,type,target,JSON.stringify(metadata)]);}
export function adminUuid(value:string){if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(value))throw new AdminError('Invalid identifier.',422);return value;}
