import "server-only";
import { createHmac, createHash, randomBytes, randomInt, timingSafeEqual } from "node:crypto";
import { database, one } from "./postgres";
import { accountSecret } from "./account-security";
import { redis } from "./redis";
const secret=accountSecret; const digest=(value:string)=>createHash("sha256").update(value).digest("hex"); const codeHash=(value:string)=>createHmac("sha256",secret()).update(value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"")).digest("hex");
async function client(){const value=redis();if(value.status==="wait")await value.connect();return value} const key=(ticket:string)=>`mfa_ticket:${digest(ticket)}`;
export async function mfaEnabled(userId:string){return (await one<{mfa_enabled:boolean}>("SELECT mfa_enabled FROM user_security WHERE user_id=$1",[userId]))?.mfa_enabled===true} export async function backupCodesLeft(userId:string){return Number((await one<{count:string}>("SELECT count(*) FROM mfa_backup_codes WHERE user_id=$1 AND used_at IS NULL",[userId]))?.count||0)}
export async function createMfaTicket(userId:string,remember:boolean){const ticket=randomBytes(32).toString("base64url");await (await client()).set(key(ticket),JSON.stringify({user_id:userId,remember,attempts:0}),"EX",300);return ticket} export async function readMfaTicket(ticket:string){const raw=await (await client()).get(key(ticket));try{const value=raw?JSON.parse(raw):null;return value&&typeof value.user_id==="string"?value as {user_id:string;remember?:boolean;attempts?:number}:null}catch{return null}} export async function clearMfaTicket(ticket:string){await (await client()).del(key(ticket))} export async function updateMfaTicket(ticket:string,value:{user_id:string;remember?:boolean;attempts?:number}){await (await client()).set(key(ticket),JSON.stringify(value),"EX",300)}
export async function consumeBackupCode(userId:string,code:string){const result=await database().query("UPDATE mfa_backup_codes SET used_at=NOW() WHERE used_at IS NULL AND id=(SELECT id FROM mfa_backup_codes WHERE user_id=$1 AND code_hash=$2 AND used_at IS NULL LIMIT 1) RETURNING id",[userId,codeHash(code)]);return result.rowCount===1} export async function replaceBackupCodes(userId:string,codes:string[]){const db=database();const connection=await db.connect();try{await connection.query("BEGIN");await connection.query("DELETE FROM mfa_backup_codes WHERE user_id=$1",[userId]);for(const code of codes)await connection.query("INSERT INTO mfa_backup_codes (user_id,code_hash) VALUES ($1,$2)",[userId,codeHash(code)]);await connection.query("INSERT INTO user_security (user_id,mfa_enabled,updated_at) VALUES ($1,TRUE,NOW()) ON CONFLICT(user_id) DO UPDATE SET mfa_enabled=TRUE,updated_at=NOW()",[userId]);await connection.query("COMMIT")}catch(error){await connection.query("ROLLBACK");throw error}finally{connection.release()}} export async function disableMfa(userId:string){const db=database();const connection=await db.connect();try{await connection.query("BEGIN");await connection.query("DELETE FROM mfa_backup_codes WHERE user_id=$1",[userId]);await connection.query("INSERT INTO user_security (user_id,mfa_enabled,updated_at) VALUES ($1,FALSE,NOW()) ON CONFLICT(user_id) DO UPDATE SET mfa_enabled=FALSE,updated_at=NOW()",[userId]);await connection.query("COMMIT")}catch(error){await connection.query("ROLLBACK");throw error}finally{connection.release()}}
export function generateBackupCodes(){const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",result:string[]=[];while(result.length<10){let raw="";for(let i=0;i<8;i++)raw+=alphabet[randomInt(alphabet.length)];const formatted=`${raw.slice(0,4)}-${raw.slice(4)}`;if(!result.includes(formatted))result.push(formatted)}return result} export function equal(value:string,expected:string){const a=Buffer.from(value),b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b)}
