import { rememberSignupIp, userIsBanned } from "@/lib/server/account-bans";
import { rememberSwitcherUser } from "@/lib/server/account-security";
﻿import { NextRequest, NextResponse } from "next/server";
import { apiError } from "@/lib/server/http";
import { clearMfaTicket, consumeBackupCode, mfaEnabled, readMfaTicket, updateMfaTicket } from "@/lib/server/mfa";
import { withinLimit } from "@/lib/server/rate-limit";
import { nativeCoreEnabled } from "@/lib/server/rollout";
import { attachSession, createSession, destroySession, revokeOtherSessions, SESSION_COOKIE } from "@/lib/server/sessions";
import { isSuspended, touchLogin, userById } from "@/lib/server/users";
export const runtime="nodejs";const ip=(r:NextRequest)=>(r.headers.get("cf-connecting-ip")||r.headers.get("x-forwarded-for")||"unknown").split(",")[0].trim();
export async function POST(request:NextRequest){if(!nativeCoreEnabled())return apiError("Not found.",404);try{if(!await withinLimit(`rl:mfa:${ip(request)}`,8,600))return apiError("Too many attempts. Please try again shortly.",429);const body=await request.json().catch(()=>null) as {ticket?:unknown;code?:unknown}|null,ticket=typeof body?.ticket==="string"?body.ticket:"",code=typeof body?.code==="string"?body.code:"",saved=await readMfaTicket(ticket);if(!saved)return apiError("That verification step expired. Sign in again.",401);const attempts=Number(saved.attempts||0)+1;if(attempts>8){await clearMfaTicket(ticket);return apiError("Too many backup-code attempts. Sign in again.",401)}const user=await userById(saved.user_id);if(!user||!await mfaEnabled(user.id)||isSuspended(user)){await clearMfaTicket(ticket);return apiError("That verification step expired. Sign in again.",401)}await rememberSignupIp(user.id,request);if(await userIsBanned(user)){await clearMfaTicket(ticket);await revokeOtherSessions(user.id);return apiError("This account is banned.",403)}if(!await consumeBackupCode(user.id,code)){await updateMfaTicket(ticket,{...saved,attempts});return apiError("That backup code is not valid.",401)}await clearMfaTicket(ticket);await destroySession(request.cookies.get(SESSION_COOKIE)?.value);const session=await createSession(user.id,request,Boolean(saved.remember));await touchLogin(user.id);const response=NextResponse.json({ok:true,redirect:process.env.MISA_DASHBOARD_URL||"/dashboard"},{headers:{"Cache-Control":"no-store"}});attachSession(response,request,session.token,session.ttl);rememberSwitcherUser(response,request,user.id);return response}catch{return apiError("Authentication is temporarily unavailable. Please try again.",503)}}
