"use client";
import { useEffect, useRef, useState } from "react";
import type { AudioTrack, LyricsRecording } from "@/lib/types";
interface Result { id:number; trackName:string; artistName:string; albumName:string; duration:number; instrumental:boolean; syncedLyrics:string|null; plainLyrics:string|null }
export function LyricsRecordingPicker({track,onChange}:{track:AudioTrack;onChange:(recording:LyricsRecording|null)=>void}) {
  const [query,setQuery]=useState("");const [results,setResults]=useState<Result[]>([]);const [status,setStatus]=useState("");const abort=useRef<AbortController|null>(null);
  useEffect(()=>()=>abort.current?.abort(),[]);
  const search=async()=>{abort.current?.abort();const controller=new AbortController();abort.current=controller;setResults([]);setStatus("Searching LRCLIB…");try{const response=await fetch(`https://lrclib.net/api/search?q=${encodeURIComponent(query.trim())}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)]),headers:{"Lrclib-Client":"Misa.lol (https://misa.lol)"}});if(!response.ok)throw new Error();const data:Result[]=await response.json();if(controller.signal.aborted)return;setResults(data.slice(0,20));setStatus(data.length?"Choose the exact recording, including its version and duration.":"No matching recording found.");}catch{if(!controller.signal.aborted)setStatus("Lyrics search temporarily unavailable. Try again later.");}};
  return <details className="mt-3 border-t border-white/10 pt-3 text-xs text-zinc-300"><summary className="cursor-pointer py-2">Lyrics recording · {track.recording?`${track.recording.artist} — ${track.recording.title}`:"Not matched"}</summary><p className="my-2 text-zinc-500">Search title and artist. Confirm the original, remix, live, slowed or sped-up version that matches your upload. Add a Synced lyrics section to display it.</p><div className="flex gap-2"><input aria-label="Find lyrics recording" type="search" value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-white/10 bg-white/5 p-2" placeholder="Title and artist" /><button type="button" disabled={!query.trim()} onClick={()=>void search()} className="rounded-lg bg-white/10 px-3 disabled:opacity-40">Search</button></div><p role="status" className="my-2">{status}</p><div className="max-h-56 overflow-auto">{results.map(item=><button type="button" key={item.id} className="my-1 block w-full rounded-lg border border-white/10 p-3 text-left hover:bg-white/10" onClick={()=>{abort.current?.abort();onChange({id:item.id,title:item.trackName,artist:item.artistName,album:item.albumName,duration:item.duration});setResults([]);setStatus("Recording confirmed. Lyrics will load automatically during playback.");}}><strong>{item.trackName} — {item.artistName}</strong><span className="mt-1 block text-zinc-400">{item.albumName} · {Math.floor(item.duration/60)}:{String(Math.round(item.duration%60)).padStart(2,"0")} · {item.instrumental?"Instrumental":item.syncedLyrics?"Synced":item.plainLyrics?"Plain text":"No lyrics"}</span></button>)}</div>{track.recording&&<button type="button" onClick={()=>onChange(null)} className="min-h-10 underline">Clear recording match</button>}<a href="https://lrclib.net" target="_blank" rel="noopener noreferrer" className="ml-3 underline">LRCLIB</a></details>;
}
