from __future__ import annotations

FEATURE_FLAG_CATALOG: tuple[tuple[str, str], ...] = (
    ("nav.overview", "Overview navigation"),
    ("nav.analytics", "Analytics navigation"),
    ("nav.badges", "Badges navigation"),
    ("nav.settings", "Settings navigation"),
    ("nav.security", "Security navigation"),
    ("nav.constellations", "Constellations navigation"),
    ("nav.customize", "Customize navigation"),
    ("nav.links", "Links navigation"),
    ("nav.leaderboard", "Leaderboard navigation"),
    ("nav.premium", "Premium navigation"),
    ("nav.templates", "Templates navigation"),
    ("customize.assets", "Assets customization"),
    ("customize.assets.avatar", "Avatar uploads"),
    ("customize.assets.background", "Background image"),
    ("customize.assets.backgroundVideo", "Background video"),
    ("customize.assets.audio", "Profile audio"),
    ("customize.assets.audioCrop", "Extract and crop audio from video"),
    ("customize.layout", "Layout customization"),
    ("customize.effects", "Effects customization"),
    ("customize.effects.username", "Username effect controls"),
    ("customize.widgets", "Widgets customization"),
    ("customize.portfolio", "Portfolio customization"),
    ("customize.sharing", "Sharing appearance"),
    ("profile.frame", "Profile frame"),
    ("profile.avatar", "Profile avatar"),
    ("profile.avatarBorder", "Avatar border"),
    ("profile.displayName", "Display name"),
    ("profile.socials", "Social links"),
    ("profile.widgets", "Profile widgets"),
    ("profile.badges", "Profile badges"),
    ("profile.audio", "Profile audio playback"),
    ("profile.views", "Profile views"),
    ("profile.joinDate", "Profile join date"),
    ("integrations.discord", "Discord integration"),
    ("feature.usernameEffects.glitch", "Glitch username effect"),
    ("feature.usernameEffects.pulse", "Pulse username effect"),


    ("feature.usernameEffects.wave", "Wave username effect"),
    ("feature.usernameEffects.shadow", "Shadow username effect"),
)
